/********************************************************************
* G__Art.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__Art.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Art();
extern void G__cpp_setup_inheritanceG__Art();
extern void G__cpp_setup_typetableG__Art();
extern void G__cpp_setup_memvarG__Art();
extern void G__cpp_setup_globalG__Art();
extern void G__cpp_setup_memfuncG__Art();
extern void G__cpp_setup_funcG__Art();
extern void G__set_cpp_environmentG__Art();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./analysisFlag.h"
#include "./EN_CsI.h"
#include "./ENFiberCal.h"
#include "./EN_Neutron.h"
#include "./ENOthers.h"
#include "./ENPlastic.h"
#include "./EN_PPAC_Cal.h"
#include "./segidlist.h"
#include "./TArtAnalysis.h"
#include "./TArtAnlEvent.h"
#include "./TArtAnlProc.h"
#include "./TArtEventSource.h"
#include "./TArtF2Param.h"
#include "./TArtF3Param.h"
#include "./TArtProc.h"
#include "./TArtRawEvent.h"
#include "./TArtSortEvent.h"
#include "./TArtSortProc.h"
#include "./TArtUnpackEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__ArtLN_TClass;
extern G__linked_taginfo G__G__ArtLN_TBuffer;
extern G__linked_taginfo G__G__ArtLN_TMemberInspector;
extern G__linked_taginfo G__G__ArtLN_TObject;
extern G__linked_taginfo G__G__ArtLN_TNamed;
extern G__linked_taginfo G__G__ArtLN_TString;
extern G__linked_taginfo G__G__ArtLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__ArtLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__ArtLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_TArrayI;
extern G__linked_taginfo G__G__ArtLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__ArtLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__ArtLN_TH1;
extern G__linked_taginfo G__G__ArtLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__ArtLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__ArtLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_EN_CsI;
extern G__linked_taginfo G__G__ArtLN_ENFiberCal;
extern G__linked_taginfo G__G__ArtLN_EN_Neutron;
extern G__linked_taginfo G__G__ArtLN_ENPlastic;
extern G__linked_taginfo G__G__ArtLN_EN_PPAC_Cal;
extern G__linked_taginfo G__G__ArtLN_TGo4CommandReceiver;
extern G__linked_taginfo G__G__ArtLN_TH2;
extern G__linked_taginfo G__G__ArtLN_TGo4WinCond;
extern G__linked_taginfo G__G__ArtLN_TGo4PolyCond;
extern G__linked_taginfo G__G__ArtLN_TGo4Parameter;
extern G__linked_taginfo G__G__ArtLN_TGo4EventElement;
extern G__linked_taginfo G__G__ArtLN_TGo4EventSource;
extern G__linked_taginfo G__G__ArtLN_TGo4EventProcessor;
extern G__linked_taginfo G__G__ArtLN_TGo4Analysis;
extern G__linked_taginfo G__G__ArtLN_TGo4UserSourceParameter;
extern G__linked_taginfo G__G__ArtLN_TArtAnalysis;
extern G__linked_taginfo G__G__ArtLN_TArtUnpackEvent;
extern G__linked_taginfo G__G__ArtLN_TArtSortEvent;
extern G__linked_taginfo G__G__ArtLN_TArtAnlEvent;
extern G__linked_taginfo G__G__ArtLN_TRandom;
extern G__linked_taginfo G__G__ArtLN_TArtF2Param;
extern G__linked_taginfo G__G__ArtLN_TArtF3Param;
extern G__linked_taginfo G__G__ArtLN_TArtAnlProc;
extern G__linked_taginfo G__G__ArtLN_TArtRawEvent;
extern G__linked_taginfo G__G__ArtLN_TArtEventStore;
extern G__linked_taginfo G__G__ArtLN_TArtEventSource;
extern G__linked_taginfo G__G__ArtLN_TArtRawEventObject;
extern G__linked_taginfo G__G__ArtLN_TArtProc;
extern G__linked_taginfo G__G__ArtLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_vectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_vectorlETArtRawATDataObjectmUcOallocatorlETArtRawATDataObjectmUgRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlETArtRawATDataObjectmUcOallocatorlETArtRawATDataObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_vectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_vectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgR;
extern G__linked_taginfo G__G__ArtLN_reverse_iteratorlEvectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ArtLN_TArtSortProc;
extern G__linked_taginfo G__G__ArtLN_TArtSortProccLcLmapping;
extern G__linked_taginfo G__G__ArtLN_TArtSortProccLcLhst1;
extern G__linked_taginfo G__G__ArtLN_TArtSortProccLcLhst2;

/* STUB derived class for protected member access */
